# Generated by Django 4.1.9 on 2023-07-16 11:59

from django.db import migrations, models
import src.models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_recipe_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='timeStamp',
            field=models.IntegerField(default=src.models.get_current_timestamp),
        ),
    ]
